### PR TITLE
Add Entity Relationship Diagram to documents

### PR DESCRIPTION
**Pull request by elberthcorniell**
In this pull request we want to add the ERD for the Ciao! social network

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @elberthcorniell! Well done with the ERD so far. There are just a few adjustments for you to make before moving forward. These include:
- [x] The `likes` entity which in your case is `reactions` has 2 primary keys. Please note that a table should only have a single primary key. Add the necessary primary key and correctly name the foreign keys.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by elberthcorniell** [comment]
> ### Changes Required! ♻️
> Hi @elberthcorniell! Well done with the ERD so far. There are just a few adjustments for you to make before moving forward. These include:
> 
> * [x]  The `likes` entity which in your case is `reactions` has 2 primary keys. Please note that a table should only have a single primary key. Add the necessary primary key and correctly name the foreign keys.
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> **Treasure Kabareebe**
> [Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

Hello @trekab, we thought about it as a composite primary key cause likes are suposed to be unique in a post + user way. So user_id and post_id are FK each one but together they are the PK of the table. Maybe we didn't expresed it in a good way in the ERD.

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

#### Great job! 👏  Both of you have done well on this project.
You've got a clean ERD diagram by the way. 👍 
Let us quickly add some finishing touches and request another review.

Speaking of the Friendship and Friendship requests model, I think we will like to know the name of our friend before making a request, let's quickly add **name** to our users' table.

[OPTIONAL CHANGES]

- [ ] I am not sure what the **like key** is doing in the reactions table which I presume is the **Like** table, after all, we want to know which user liked which post as well as how many likes a post has.

- [ ] I am not sure what the **private and status** key is doing in the posts table, we are trying to keep it simple here, remember? MVP. Likewise, the status key in the comments table, except you are going to approve a comment before allowing them to show up which is actually a cool feature. But if you not going to do that, just keep it simple for now. Nice one by the way.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by krys2fa — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this milestone approved. 🏆  

You can now merge this branch into the development branch and go on with the next milestone.

💡  Do not forget to submit your project completion form after merging this branch.
💡 Also, it'll be great to implement the optional changes requested by the previous reviewer.

All the best team!

**Pull request merged**
